# Generated by Django 3.0.4 on 2020-04-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegefoods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='category',
            field=models.CharField(choices=[('V', 'Vegetables'), ('F', 'Fruits'), ('D', 'Dry Fruits'), ('J', 'Juices')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
