# Generated by Django 3.0.4 on 2020-04-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegefoods', '0002_items_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
