# Generated by Django 3.0.4 on 2020-04-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegefoods', '0003_items_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='discount_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
