# Generated by Django 3.0.4 on 2020-04-27 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vegefoods', '0010_billinginfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billinginfo',
            name='user',
        ),
    ]
