# Generated by Django 3.0.4 on 2020-04-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegefoods', '0012_billinginfo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billinginfo',
            name='user',
        ),
        migrations.AddField(
            model_name='billinginfo',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
